language: ruby

sudo: false

rvm:      
  - 2.3

install: 'echo skip bundle install'

script:
  - export WORKSPACE=`pwd`/workspace
  - export PATH_TO_DMSF=`pwd`
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - cp config/database.yml.travis $WORKSPACE/database.yml
  - bash -x ./test/ci/redmine_install.sh -r
  - bash -x ./test/ci/redmine_install.sh -i
  - bash -x ./test/ci/redmine_install.sh -t
  - bash -x ./test/ci/redmine_install.sh -u